apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.2
        env:
        - name: POSTGRES_DB
          value: crud
        - name: POSTGRES_USER
          value: crud
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
